/* Generated by ts-rs from Rust struct db::AdRow. Regenerate with: cd src-tauri && cargo test */

export type AdRow = {
  id: number;
  content: string | null;
  hook: string | null;
  emotion: string | null;
  offer: string | null;
  audience: string | null;
  source: string | null;
  created_at: string | null;
};
