/* Generated by ts-rs from Rust struct sec::CompanyTickerRow. Regenerate with: cd src-tauri && cargo test */

export type CompanyTickerRow = {
  cik_str: number;
  ticker: string;
  title: string;
};
