/* Generated by ts-rs from Rust struct sec::FilingSummary. Regenerate with: cd src-tauri && cargo test */

export type FilingSummary = {
  form: string;
  description: string;
  filing_date: string;
  accession_number: string;
};
