/* Generated by ts-rs from Rust struct db::PatternStats. Regenerate with: cd src-tauri && cargo test */

export type PatternStats = {
  hooks: [string, number][];
  emotions: [string, number][];
  offers: [string, number][];
};
