/* Generated by ts-rs from Rust struct db::VerifiedEmailRow. Regenerate with: cd src-tauri && cargo test */

export type VerifiedEmailRow = {
  email: string;
  status: string;
  quality: string;
  verified_at: string | null;
  syntax_ok: number | null;
  mx_ok: number | null;
  disposable_ok: number | null;
};
