/* Generated by ts-rs from Rust struct email_verify::VerifyResult. Regenerate with: cd src-tauri && cargo test */

import type { VerifyStatus } from "./VerifyStatus";
import type { VerifyTests } from "./VerifyTests";

export type VerifyResult = {
  email: string;
  status: VerifyStatus;
  quality: string;
  tests: VerifyTests;
};
