/* Generated by ts-rs from Rust struct email_verify::VerifyTests. Regenerate with: cd src-tauri && cargo test */

export type VerifyTests = {
  syntax: boolean;
  disposable: boolean;
  mx: boolean;
};
